// Generated by IcedCoffeeScript 108.0.8
(function() {
  var ModalDialogController, baseScope, offset;

  offset = function(element) {
    var doc, docElement, rect;
    rect = element.getBoundingClientRect();
    doc = element && element.ownerDocument;
    docElement = doc.documentElement;
    return {
      top: (rect.top + (window.pageYOffset || docElement.scrollTop) - (docElement.clientTop || 0)) + 'px',
      left: (rect.left + (window.pageXOffset || docElement.scrollLeft) - (docElement.clientLeft || 0)) + 'px'
    };
  };

  ModalDialogController = (function() {
    function ModalDialogController($scope, $element) {
      this.showDialog = false;
      this.closeOnClick = this.closeOnClick || true;
      this.showClose = this.showClose || true;
      this.calloutType = this.calloutType || 'none';
      this.show = (function(_this) {
        return function(args) {
          if (args.event) {
            _this.offset = offset(args.event.target);
          }
          if (args.url) {
            _this.src = args.url;
          }
          return _this.showDialog = true;
        };
      })(this);
      this.hide = (function(_this) {
        return function() {
          return _this.showDialog = false;
        };
      })(this);
      this.clickOverlay = (function(_this) {
        return function() {
          if (_this.closeOnClick) {
            return _this.showDialog = false;
          }
        };
      })(this);
    }

    return ModalDialogController;

  })();

  baseScope = {
    dcStyle: '@',
    dcClass: '@',
    show: '=dcShow',
    hide: '=dcHide',
    closeOnClick: '@dcCloseOnClick',
    showClose: '@dcShowClose',
    isCallout: '=dcIsCallout',
    calloutPosition: '@dcCalloutPosition',
    src: '@'
  };

  angular.module('dcModalDialogModule', []).directive('dcModalDialog', function() {
    return {
      controller: ModalDialogController,
      controllerAs: 'dcModalDialogCtl',
      bindToController: true,
      link: function(scope, element, attrs) {},
      replace: true,
      templateUrl: '/Content/popup.html',
      transclude: true,
      scope: baseScope
    };
  }).directive('dcModalIframe', function() {
    return {
      controller: ModalDialogController,
      controllerAs: 'dcModalDialogCtl',
      bindToController: true,
      link: function(scope, element, attrs) {},
      replace: true,
      templateUrl: '/Content/iframe.html',
      scope: baseScope
    };
  });

}).call(this);
